[package]
name = "computorv2"
version = "0.1.1"
authors = ["Guilhem Smith <gsmith@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "5.0.3"
colored = "1.8.0"